name: Syntax check

on: [push, pull_request]

jobs:
  syntax:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: ['8.2', '8.3']

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run syntax check
        run: |
          if find . -name "*.php" ! -path "./vendor/*" -exec php -l {} 2>&1 \; | grep "syntax error, unexpected"; then exit 1; fi

  phpcs:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: ['8.2']

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run PHPCS
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar .